apiVersion: apps/v1
kind: Deployment
metadata:
    name: meeting
spec:
    replicas: 1
    selector:
        matchLabels:
            app: meeting
    template:
        metadata:
            labels:
                app: meeting
        spec:
            containers:
                - name: meeting
                  image: $CONTAINER_REGISTRY_LOGIN_SERVER/meeting:$VERSION
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5002
                  # volumeMounts:
                  #     - name: meeting-service-secret
                  #       mountPath: /
                  #       readOnly: true
                  env:
                      - name: MEETING_SERVICE_PORT
                        value: $MEETING_SERVICE_PORT
                      - name: MONGODB_URI
                        value: $MONGODB_URI
                      - name: MSG_QUEUE_URL
                        value: $MSG_QUEUE_URL
                      - name: EXCHANGE_NAME
                        value: $EXCHANGE_NAME
                      - name: APP_SECRET
                        value: $APP_SECRET
                  #     - name: MEETING_SERVICE_PORT
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: meeting-secret
                  #               key: meeting_service_port
                  #     - name: MONGODB_URI
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: meeting-secret
                  #               key: mongodb_uri
                  #     - name: MSG_QUEUE_URL
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: meeting-secret
                  #               key: msg_queue_url
                  #     - name: EXCHANGE_NAME
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: meeting-secret
                  #               key: exchange_name
                  #     - name: APP_SECRET
                  #       valueFrom:
                  #           secretKeyRef:
                  #               name: meeting-secret
                  #               key: app_secret

                  resources:
                      requests:
                          cpu: 126m
                          memory: 512Mi
                      limits:
                          cpu: 256m
                          memory: 1024Mi
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: 5002
                      initialDelaySeconds: 15
                      periodSeconds: 20
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 5002
                      initialDelaySeconds: 5
                      periodSeconds: 10
            # volumes:
            #     - name: meeting-service-secret
            #       secret:
            #           secretName: meeting-secret
---
apiVersion: v1
kind: Service
metadata:
    name: meeting
spec:
    selector:
        app: meeting
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5002
