apiVersion: apps/v1
kind: Deployment
metadata:
    name: meeting
spec:
    replicas: 1
    selector:
        matchLabels:
            app: meeting
    template:
        metadata:
            labels:
                app: meeting
        spec:
            containers:
                - name: meeting
                  image: $CONTAINER_REGISTRY_LOGIN_SERVER/meeting:$VERSION
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5002
                  env:
                      - name: MEETING_SERVICE_PORT
                        value: "5002"
                  resources:
                      requests:
                          cpu: 126m
                          memory: 512Mi
                      limits:
                          cpu: 256m
                          memory: 1024Mi
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: 5002
                      initialDelaySeconds: 15
                      periodSeconds: 20
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 5002
                      initialDelaySeconds: 5
                      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
    name: meeting
spec:
    selector:
        app: meeting
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5002
