apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-cpu-memory
spec:
    minReplicas: 1
    maxReplicas: 10
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway-deployment
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 30
        - type: Resource
          resource:
              name: memory
              target:
                  type: AverageValue
                  averageValue: 10Mi
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 5
        scaleUp:
            stabilizationWindowSeconds: 0
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 5
