apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/frontend:$VERSION
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 126m
              memory: 2048Mi
            limits:
              cpu: 256m
              memory: 4096Mi

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
