apiVersion: apps/v1
kind: Deployment
metadata:
    name: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user
                  image: $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5001
                  volumeMounts:
                      - name: user-service-secret
                        mountPath: /
                        readOnly: true
                  # env:
                  # - name: USER_SERVICE_PORT
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: meeting_service_port
                  # - name: MONGODB_URI
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: mongodb_uri
                  # - name: MSG_QUEUE_URL
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: msg_queue_url
                  # - name: EXCHANGE_NAME
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: exchange_name
                  # - name: ACCESS_TOKEN_SECRET
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: access_token_secret
                  # - name: REFRESH_TOKEN_SECRET
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: refresh_token_secret
                  # - name: ACCESS_TOKEN_DURATION
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: access_token_duration
                  # - name: REFRESH_TOKEN_DURATION
                  #   valueFrom:
                  #       secretKeyRef:
                  #           name: user-secret
                  #           key: refresh_token_duration
                  resources:
                      requests:
                          cpu: 126m
                          memory: 512Mi
                      limits:
                          cpu: 256m
                          memory: 1024Mi
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: 5001
                      initialDelaySeconds: 15
                      periodSeconds: 20
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 5001
                      initialDelaySeconds: 5
                      periodSeconds: 10
            volumes:
                - name: user-service-secret
                  secret:
                      secretName: user-secret
---
apiVersion: v1
kind: Service
metadata:
    name: user
spec:
    selector:
        app: user
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5001
