apiVersion: apps/v1
kind: Deployment
metadata:
    name: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user
                  image: $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5001
                  env:
                      - name: PORT
                        value: "5001"
                  resources:
                      requests:
                          cpu: 126m
                          memory: 512Mi
                      limits:
                          cpu: 256m
                          memory: 1024Mi
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: 5001
                      initialDelaySeconds: 15
                      periodSeconds: 20
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 5001
                      initialDelaySeconds: 5
                      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
    name: user
spec:
    selector:
        app: user
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5001
